from .chef import Chef
from .empath import Empath
from .fortune_teller import FortuneTeller
from .investigator import Investigator
from .librarian import Librarian
from .mayor import Mayor
from .monk import Monk
from .ravenkeeper import RavenKeeper
from .slayer import Slayer
from .soldier import Soldier
from .undertaker import UnderTaker
from .virgin import Virgin
from .washerwoman import WasherWoman
